### ISSUE TITLE
This not a issue

### ISSUE THREAD

**Issue by RusithKarunarathne** [SheaGuev/JavaRestAPI_HealthCareServiceAPI#1]
Can you please let me know how to test this on localhost. please contact me soon.  Also can you make a screen video and send it to me.  Is the course work completely done?

please drop a message
Fb:- https://www.facebook.com/rusith.thathsara.1
whatsapp: +94701612572
email: rusithkarunarathne@gmail.com

@SheaGuev

**Comment by SheaGuev** [comment]
> Can you please let me know how to test this on localhost. please contact me soon. Also can you make a screen video and send it to me. Is the course work completely done?
> 
> please drop a message Fb:- https://www.facebook.com/rusith.thathsara.1 whatsapp: +94701612572 email: [rusithkarunarathne@gmail.com](mailto:rusithkarunarathne@gmail.com)
> 
> @SheaGuev

Hi there, did you have any luck?

You can clone or download the repository and you will have to build it with an IDE. It was made with Netbeans so if you download an apache tomcat server, and install it into netbeans, you can run it through a web app in Netbeans.

Also the coursework is not completely done but it will be finalised at the end of the week.

**Comment by RusithKarunarathne** [comment]
are u done this ?

**Comment by SheaGuev** [comment]
> are u done this ?

Yes I added the final touches a few days ago.
